### ISSUE TITLE
CHARMM: Update to latest c36 input files

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#12]
We may want to make sure we have the latest CHARMM 36 input files from the Mackerell [CHARMM Force Field Files page](http://mackerell.umaryland.edu/charmm_ff.shtml)

**Comment by jchodera** [comment]
The latest update seems to be July 2016, but we might ping the MacKerell lab and see if there have been any updates/fixes since then.

**Comment by ChayaSt** [comment]
According to Alex MacKerell, these files are the latest ones.
