### ISSUE TITLE
CHARMM: Ensure correct CHARMM metapackage will be built

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#16]
We will want to make sure the metapackage includes all files that can be properly converted and combined, while excluding those that contain problematic parameters (until they are fixed by the CHARMM folks).

**Comment by jchodera** [comment]
Since the conversion generates a single XML file, we don't need to have metapackages.

**Comment by jchodera** [comment]
@ChayaSt : I am getting a bunch of warnings like this when I run the conversion script:
```
lski1962:charmm choderaj$ python -i convert_charmm.py 
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'CHL1'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'CHNS'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'CHM1'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'DMPR'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'MGU1'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'MGU2'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'NIC'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'NICH'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'PPI1'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'PPI2'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'AMP'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'ADP'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'ATP'
  resname, ParameterWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py:797: ParameterWarning: Replacing residue 'NAD'
  resname, ParameterWarning)
...
```
Is this problematic? Any idea why these warnings appear?

**Comment by ChayaSt** [comment]
@jchodera, there are duplicate residues with different names but with the same topology strewn about in the different files. I haven't looked into all of them to ensure that none of them are problematic but it's on my list.

**Comment by jchodera** [comment]
I've created a CHARMM metapackage that combines CHARMM36 (without waters) with the default waters and ions: 
```xml
<ForceField>
  <Include file="charmm36_nowaters.xml"/>
  <Include file="waters_ions_default.xml"/>
</ForceField>
```
This causes a residue name collision with `TM3P`:
```python
>>> from simtk.openmm import app
>>> ff = app.ForceField('charmm.xml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 178, in __init__
    self.loadFile(files)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 237, in loadFile
    self.loadFile(includeFile)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 286, in loadFile
    self.registerResidueTemplate(template)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 411, in registerResidueTemplate
    raise ValueError('Residue template %s with the same override level %d already exists.' % (template.name, template.overrideLevel))
ValueError: Residue template TM3P with the same override level 0 already exists.
```
The residue name `TM3P` occurs in
* [`toppar/top_all36_cgenff.rtf`](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/top_all36_cgenff.rtf) where it is "C5H9O5P 4'-methyl,3'-phosphate tetrahydrofuran (phosphate -2)"
* [`toppar/stream/na/toppar_all36_na_model.str`](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/stream/na/toppar_all36_na_model.str#L1682) where it is "4'-methyl,3'-phosphate tetrahydrofuran (phosphate -2)" but notes "This is the RNA version of TM3P" 
* [`toppar/stream/misc/toppar_ions_won.str`](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/stream/misc/toppar_ions_won.str#L339-L342) where it is a "Thulium +3 ion", which is actually `Tm3p` but converted to `TM3P`.

@peastman: We skip the second file (because of conflicts and inconsistencies), but we need to figure out how to handle the third file with the Thulium ion. That file is
```
* top_ions_won.str: general model for mono-, di-, and trivalent cations
```
We can potentially omit it, since there are some common ions in the standard water and ions file ([`toppar/toppwar_water_ions.str`](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/toppar_water_ions.str)) but we should decide on a more general strategy for handling these kinds of residue conflicts. Some options:
* Make residue names case-sensitive rather than all-caps. Would OpenMM accept `TM3P` and `Tm3p` as distinct?
* Add arbitrary prefixes to residue names. Are there any limitations on residue names?
* Something else?

**Comment by jchodera** [comment]
Note that it's not just the residue name, it's an atom name too:
```
Mass 366 Tm3p 168.93   Tm ! Thulium
...
RESI Tm3p 3.00 ! Thulium +3 ion
GROUP
ATOM Tm3p Tm3p 3.00
PATCH FIRST NONE LAST NONE
```

**Comment by jchodera** [comment]
It looks like OpenMM's `ForceField` is OK with having both `TM3P` and `Tm3p`, so I'll see if I can figure out where the conversion to uppercase is happening and prevent that from happening.

**Comment by jchodera** [comment]
The conversion to uppercase seems to be occurring in ParmEd, which seems to have a number of places where names are converted to uppercase for reasons I don't understand. I've posted an issue  https://github.com/ParmEd/ParmEd/issues/919 to see if we can modify ParmEd to avoid this conversion.

**Comment by jchodera** [comment]
A functioning CHARMM36 metapackage is being built now that #42 has been merged.
