### ISSUE TITLE
AMBER: Update for AmberTools17 release

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#17]
The AmberTools17 release is imminent, but we want to include both 16 and 17.

**Comment by rafwiewiora** [comment]
This will be done on the weekend.

**Comment by jchodera** [comment]
Travis is now testing AmberTools 17 as of #35.

AmberTools 17 is now available via `conda` with
```
conda install --yes -c http://ambermd.org/downloads/ambertools/conda/ ambertools
```
We'll probably want to copy the package over to the `omnia` channel.

We still need to rebuild the `ffxml` files for AmberTools 17.

**Comment by jchodera** [comment]
All AMBER `ffxml` files have been updated in #37
