### ISSUE TITLE
AMBER: Automate testing of conversion scripts and resulting converted parameters via travis

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#18]

**Comment by rafwiewiora** [comment]
This will be done on the weekend.

**Comment by jchodera** [comment]
This is already being done for the AMBER conversion. The `convert_amber.py` script automatically tests all of the converted `ffxml` files to ensure energies agree for the battery test systems.

We just have to automate the CHARMM testing as well.
