### ISSUE TITLE
AMBER: Identify recommended combinations of corresponding ffxml files in README docs and meta-XML files

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#20]
We need to include recommended sets of monovalent and divalent counterions with recommended water models.

Can we recommend TIP4P-Ew by default, or are there no ion models that are recommended for compatibility?

**Comment by jchodera** [comment]
Considerations:
* Make sure that users can use other water models (e.g. TIP4PFB)
* Ions can be mixed-and-matched, but a meta-package will give recommended combinations

**Comment by rafwiewiora** [comment]
This is nearly done, testing now.

**Comment by rafwiewiora** [comment]
As for water+ions, they're packaged as recommended in Amber Tools 17 - in 'standard' sets (TIP3P, TIP4P-Ew, SPC/E, the FB waters should be added in the future): water + "Joung-Chetham monovalent ions + Li/Merz highly charged ions (+2 to +4, 12-6 normal usage set); and we also have `HFE` and `IOD` Li/Merz +2 to +4 sets which can override the standard. 

As for protein - nucleic combinations - from Amber Tools 16 the protein and nucleic acid parameters have been separated - i.e. now we have `protein.ff14SB.xml`, which can be combined with some of the DNA or RNA choices - see Amber 17 manual (http://ambermd.org/doc12/Amber17.pdf) page 33 for recommended combinations - these will have to be achieved, if you want to have them, through the meta-XML files. Pre- Amber Tools 16 forcefields are also converted (from `oldff`), e.g. `ff14SB.xml`, which contains a pre-made protein + DNA/RNA mix.

**Comment by jchodera** [comment]
@peastman : I've updated the AMBER forcefields for AmberTools17 [here](https://github.com/choderalab/openmm-forcefields/tree/master/amber/ffxml). You'll have to pick and choose the ones you want in OpenMM 7.2.

Note @rafwiewiora's comments above where, if you want to combine protein and nucleic acids, you'll have to write an XML metapackage to import the desired combination.

**Comment by jchodera** [comment]
@peastman : You should be good to go here. Let me know if you need further information not contained in the provided docs or the [Amber17 manual](http://ambermd.org/doc12/Amber17.pdf).

**Comment by peastman** [comment]
Could we discuss this in the OpenMM repo at https://github.com/pandegroup/openmm/issues/1611?  Other people know the Amber force fields a lot better than I do, so I'd like to get feedback on which combinations are recommended.

**Comment by jchodera** [comment]
Absolutely!

**Comment by jchodera** [comment]
See https://github.com/pandegroup/openmm/issues/1611#issuecomment-338523225

**Comment by jchodera** [comment]
The recommended files to include, based on [this comment](https://github.com/pandegroup/openmm/issues/1611#issuecomment-339755805), are:
```
protein.ff14SB.xml
DNA.OL15.xml
DNA.bsc1.xml
RNA.OL3.xml
lipid17_merged.xml (renamed to lipid17.xml)
tip3p_standard.xml (renamed to tip3p.xml)
spce_standard.xml (renamed to spce.xml)
tip4pew_standard.xml (renamed to tip4pew.xml)
TIP3P-FB
TIP4P-FB
leaprc.protein.ff15ipq (if possible; has torsion bugs)
```

**Comment by jchodera** [comment]
As per https://github.com/choderalab/openmm-forcefields/issues/44#issuecomment-345344580, we will omit `leaprc.protein.ff15ipq` from inclusion in OpenMM 7.2 unless an update of AmberTools with the corrected leaprc file is issued in time for OpenMM 7.2 testing/release.

**Comment by peastman** [comment]
Correction: we will include it in the beta, since it looks probable the AmberTools update will come out in time.  If for any reason it doesn't, we'll remove the file from the release.

**Comment by jchodera** [comment]
I'd have to manually modify my AmberTools installation to do that---something I was very much hoping to avoid because (1) it's a terrible manual hack, (2) we can get into a lot of trouble if we forget to remove it, and (3) we will have to update the conversion again and test everything once more at that point prior to release.

**Comment by peastman** [comment]
> (1) it's a terrible manual hack

No, it's a very straightforward solution.  That file will be in the next release.  That release isn't out yet.  So add it to the current release.

> 2) we can get into a lot of trouble if we forget to remove it

So remove it as soon as you're done generating the XML.

> (3) we will have to update the conversion again and test everything once more at that point prior to release.

The only thing we'll need to do is diff the version of the file in the release against the one used now to make sure they're really identical.  @dscerutti they will be, right?

**Comment by jchodera** [comment]
From https://github.com/choderalab/openmm-forcefields/issues/44#issuecomment-345552999:
> Working on a little more validation now; I will have the patch committed shortly.

That sounds to me like it's not at all certain [this file](https://github.com/choderalab/openmm-forcefields/files/1466469/parm15ipq_10.3.zip) will be the final version.

Under strong protest, I have done as you asked @peastman in https://github.com/choderalab/openmm-forcefields/pull/49

**Comment by jchodera** [comment]
It sounds like @dscerutti has included this specific version of `parm15ipq_10.3.dat` in the AMBER tree:
https://github.com/choderalab/openmm-forcefields/pull/49#issuecomment-346483909

**Comment by dscerutti** [comment]
The file has been modified to meet the OpenMM / tleap compatibility
standards in both the release version (patch #7 or so) and in the master
dev branch.

**Comment by jchodera** [comment]
@dscerutti : Just to confirm: the file included in AmberTools is *identical* to the one you provided us, correct? I'm just a bit worried by the phrasing "the file has been modified"...

**Comment by dscerutti** [comment]
Yes, it is identical.

**Comment by jchodera** [comment]
Thanks!
