### ISSUE TITLE
AMBER: Add tests for script to create merged lipid residue ffxml from lipid component xml files

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#24]
I'm not clear on all the issues here, but AMBER lipids may require some special handling. @peastman can elaborate on what precisely needs to be done.

cc: pandegroup/openmm#1611 (comment)

**Comment by peastman** [comment]
More specifically, see https://github.com/pandegroup/openmm/issues/1611#issuecomment-288890709.

**Comment by jchodera** [comment]
Following the discussion @rafwiewiora and I have had, the only reasonable way to support this is to allow users to follow the same procedure used in AMBER where a preprocessing script is used to convert their PDB file into one with the appropriate residue names prior to parameterization. This will be documented in the AMBER conversion README.

**Comment by rafwiewiora** [comment]
I'm looking into this more to get 100% sure I was right in what I was saying.

**Comment by peastman** [comment]
That's clearly not true.  I was able to merge a few templates by hand to create a single POPC template, so it's certainly possible.  We need to decide which lipids we're supporting and have the converter do that automatically.

**Comment by jchodera** [comment]
It may be possible, but it certainly doesn't seem reasonable to merge them by hand.

For an automated merging scheme, how would we specify what lipids are to be merged, and how many would we have to map out by hand? What steps does the merging process consist of? Do you want to invest the time in writing an automated merging script? And is the benefit worth the effort given there is a workflow that does not require this?

**Comment by jchodera** [comment]
Oh, shoot, I'm guessing that the issue here is that your automated membrane protein pipeline assumes no preprocessing step, so we need to merge the lipids for your pipeline to work with Amber forcefields. Is that right?

**Comment by jchodera** [comment]
@peastman: Digging into `lipid14`, it looks like the number of possible combinations is actually very small, so this should be doable if you can give guidance about what you did to merge the lipid parameters manually.

"Currently, there are four tail group residues and two head group residues supported, as well as cholesterol, and LEaP supports any combination of these lipid residues"

That's a very minimal amount of information we have to manually specify.

**Comment by peastman** [comment]
Here is my manually merged POPC template.  The things I did were 1) prefix each atom name with the template name, since the templates had overlapping names, and 2) replace the `<ExternalBond>` tags with the appropriate `<Bond>` tags (the last two lines at the very end).

To automate this, we would need to specify the following information for each lipid:

1. What templates to merge.
2. What bonds to add between them.
3. What to name the merged residue.

```xml
  <Residue name="POPC">
   <Atom name="OL-C12" type="cD" charge="-0.143418"/>
   <Atom name="OL-H2R" type="hL" charge="0.04286"/>
   <Atom name="OL-H2S" type="hL" charge="0.04286"/>
   <Atom name="OL-C13" type="cD" charge="0.001619"/>
   <Atom name="OL-H3R" type="hL" charge="0.019529"/>
   <Atom name="OL-H3S" type="hL" charge="0.019529"/>
   <Atom name="OL-C14" type="cD" charge="-0.02296"/>
   <Atom name="OL-H4R" type="hL" charge="0.018134"/>
   <Atom name="OL-H4S" type="hL" charge="0.018134"/>
   <Atom name="OL-C15" type="cD" charge="-0.016692"/>
   <Atom name="OL-H5R" type="hL" charge="0.00869"/>
   <Atom name="OL-H5S" type="hL" charge="0.00869"/>
   <Atom name="OL-C16" type="cD" charge="-0.023789"/>
   <Atom name="OL-H6R" type="hL" charge="0.009266"/>
   <Atom name="OL-H6S" type="hL" charge="0.009266"/>
   <Atom name="OL-C17" type="cD" charge="-0.017495"/>
   <Atom name="OL-H7R" type="hL" charge="0.019598"/>
   <Atom name="OL-H7S" type="hL" charge="0.019598"/>
   <Atom name="OL-C18" type="cD" charge="0.031775"/>
   <Atom name="OL-H8R" type="hL" charge="0.032685"/>
   <Atom name="OL-H8S" type="hL" charge="0.032685"/>
   <Atom name="OL-C19" type="cB" charge="-0.244228"/>
   <Atom name="OL-H9R" type="hB" charge="0.131512"/>
   <Atom name="OL-C110" type="cB" charge="-0.239284"/>
   <Atom name="OL-H10R" type="hB" charge="0.126878"/>
   <Atom name="OL-C111" type="cD" charge="0.029059"/>
   <Atom name="OL-H11R" type="hL" charge="0.033531"/>
   <Atom name="OL-H11S" type="hL" charge="0.033531"/>
   <Atom name="OL-C112" type="cD" charge="-0.026353"/>
   <Atom name="OL-H12R" type="hL" charge="0.019717"/>
   <Atom name="OL-H12S" type="hL" charge="0.019717"/>
   <Atom name="OL-C113" type="cD" charge="-0.018257"/>
   <Atom name="OL-H13R" type="hL" charge="0.0138"/>
   <Atom name="OL-H13S" type="hL" charge="0.0138"/>
   <Atom name="OL-C114" type="cD" charge="-0.024849"/>
   <Atom name="OL-H14R" type="hL" charge="0.008572"/>
   <Atom name="OL-H14S" type="hL" charge="0.008572"/>
   <Atom name="OL-C115" type="cD" charge="-0.023247"/>
   <Atom name="OL-H15R" type="hL" charge="0.010403"/>
   <Atom name="OL-H15S" type="hL" charge="0.010403"/>
   <Atom name="OL-C116" type="cD" charge="-0.012488"/>
   <Atom name="OL-H16R" type="hL" charge="0.013659"/>
   <Atom name="OL-H16S" type="hL" charge="0.013659"/>
   <Atom name="OL-C117" type="cD" charge="0.008684"/>
   <Atom name="OL-H17R" type="hL" charge="0.010026"/>
   <Atom name="OL-H17S" type="hL" charge="0.010026"/>
   <Atom name="OL-C118" type="cD" charge="-0.11729"/>
   <Atom name="OL-H18R" type="hL" charge="0.026627"/>
   <Atom name="OL-H18S" type="hL" charge="0.026627"/>
   <Atom name="OL-H18T" type="hL" charge="0.026627"/>
   <Bond atomName1="OL-C12" atomName2="OL-H2R"/>
   <Bond atomName1="OL-C12" atomName2="OL-H2S"/>
   <Bond atomName1="OL-C12" atomName2="OL-C13"/>
   <Bond atomName1="OL-C13" atomName2="OL-H3R"/>
   <Bond atomName1="OL-C13" atomName2="OL-H3S"/>
   <Bond atomName1="OL-C13" atomName2="OL-C14"/>
   <Bond atomName1="OL-C14" atomName2="OL-H4R"/>
   <Bond atomName1="OL-C14" atomName2="OL-H4S"/>
   <Bond atomName1="OL-C14" atomName2="OL-C15"/>
   <Bond atomName1="OL-C15" atomName2="OL-H5R"/>
   <Bond atomName1="OL-C15" atomName2="OL-H5S"/>
   <Bond atomName1="OL-C15" atomName2="OL-C16"/>
   <Bond atomName1="OL-C16" atomName2="OL-H6R"/>
   <Bond atomName1="OL-C16" atomName2="OL-H6S"/>
   <Bond atomName1="OL-C16" atomName2="OL-C17"/>
   <Bond atomName1="OL-C17" atomName2="OL-H7R"/>
   <Bond atomName1="OL-C17" atomName2="OL-H7S"/>
   <Bond atomName1="OL-C17" atomName2="OL-C18"/>
   <Bond atomName1="OL-C18" atomName2="OL-H8R"/>
   <Bond atomName1="OL-C18" atomName2="OL-H8S"/>
   <Bond atomName1="OL-C18" atomName2="OL-C19"/>
   <Bond atomName1="OL-C19" atomName2="OL-H9R"/>
   <Bond atomName1="OL-C19" atomName2="OL-C110"/>
   <Bond atomName1="OL-C110" atomName2="OL-H10R"/>
   <Bond atomName1="OL-C110" atomName2="OL-C111"/>
   <Bond atomName1="OL-C111" atomName2="OL-H11R"/>
   <Bond atomName1="OL-C111" atomName2="OL-H11S"/>
   <Bond atomName1="OL-C111" atomName2="OL-C112"/>
   <Bond atomName1="OL-C112" atomName2="OL-H12R"/>
   <Bond atomName1="OL-C112" atomName2="OL-H12S"/>
   <Bond atomName1="OL-C112" atomName2="OL-C113"/>
   <Bond atomName1="OL-C113" atomName2="OL-H13R"/>
   <Bond atomName1="OL-C113" atomName2="OL-H13S"/>
   <Bond atomName1="OL-C113" atomName2="OL-C114"/>
   <Bond atomName1="OL-C114" atomName2="OL-H14R"/>
   <Bond atomName1="OL-C114" atomName2="OL-H14S"/>
   <Bond atomName1="OL-C114" atomName2="OL-C115"/>
   <Bond atomName1="OL-C115" atomName2="OL-H15R"/>
   <Bond atomName1="OL-C115" atomName2="OL-H15S"/>
   <Bond atomName1="OL-C115" atomName2="OL-C116"/>
   <Bond atomName1="OL-C116" atomName2="OL-H16R"/>
   <Bond atomName1="OL-C116" atomName2="OL-H16S"/>
   <Bond atomName1="OL-C116" atomName2="OL-C117"/>
   <Bond atomName1="OL-C117" atomName2="OL-H17R"/>
   <Bond atomName1="OL-C117" atomName2="OL-H17S"/>
   <Bond atomName1="OL-C117" atomName2="OL-C118"/>
   <Bond atomName1="OL-C118" atomName2="OL-H18R"/>
   <Bond atomName1="OL-C118" atomName2="OL-H18S"/>
   <Bond atomName1="OL-C118" atomName2="OL-H18T"/>
   <Atom name="PA-C116" type="cD" charge="-0.125447"/>
   <Atom name="PA-H16R" type="hL" charge="0.029046"/>
   <Atom name="PA-H16S" type="hL" charge="0.029046"/>
   <Atom name="PA-H16T" type="hL" charge="0.029046"/>
   <Atom name="PA-C115" type="cD" charge="0.013975"/>
   <Atom name="PA-H15R" type="hL" charge="0.009292"/>
   <Atom name="PA-H15S" type="hL" charge="0.009292"/>
   <Atom name="PA-C114" type="cD" charge="-0.020086"/>
   <Atom name="PA-H14R" type="hL" charge="0.015929"/>
   <Atom name="PA-H14S" type="hL" charge="0.015929"/>
   <Atom name="PA-C113" type="cD" charge="-0.033096"/>
   <Atom name="PA-H13R" type="hL" charge="0.014621"/>
   <Atom name="PA-H13S" type="hL" charge="0.014621"/>
   <Atom name="PA-C112" type="cD" charge="-0.027633"/>
   <Atom name="PA-H12R" type="hL" charge="0.011368"/>
   <Atom name="PA-H12S" type="hL" charge="0.011368"/>
   <Atom name="PA-C111" type="cD" charge="-0.025206"/>
   <Atom name="PA-H11R" type="hL" charge="0.014334"/>
   <Atom name="PA-H11S" type="hL" charge="0.014334"/>
   <Atom name="PA-C110" type="cD" charge="-0.028831"/>
   <Atom name="PA-H10R" type="hL" charge="0.014691"/>
   <Atom name="PA-H10S" type="hL" charge="0.014691"/>
   <Atom name="PA-C19" type="cD" charge="-0.030472"/>
   <Atom name="PA-H9R" type="hL" charge="0.013897"/>
   <Atom name="PA-H9S" type="hL" charge="0.013897"/>
   <Atom name="PA-C18" type="cD" charge="-0.015793"/>
   <Atom name="PA-H8R" type="hL" charge="0.009067"/>
   <Atom name="PA-H8S" type="hL" charge="0.009067"/>
   <Atom name="PA-C17" type="cD" charge="-0.01963"/>
   <Atom name="PA-H7R" type="hL" charge="0.011041"/>
   <Atom name="PA-H7S" type="hL" charge="0.011041"/>
   <Atom name="PA-C16" type="cD" charge="-0.024427"/>
   <Atom name="PA-H6R" type="hL" charge="0.013334"/>
   <Atom name="PA-H6S" type="hL" charge="0.013334"/>
   <Atom name="PA-C15" type="cD" charge="-0.029387"/>
   <Atom name="PA-H5R" type="hL" charge="0.016763"/>
   <Atom name="PA-H5S" type="hL" charge="0.016763"/>
   <Atom name="PA-C14" type="cD" charge="-0.030099"/>
   <Atom name="PA-H4R" type="hL" charge="0.020877"/>
   <Atom name="PA-H4S" type="hL" charge="0.020877"/>
   <Atom name="PA-C13" type="cD" charge="-0.004882"/>
   <Atom name="PA-H3R" type="hL" charge="0.019007"/>
   <Atom name="PA-H3S" type="hL" charge="0.019007"/>
   <Atom name="PA-C12" type="cD" charge="-0.149259"/>
   <Atom name="PA-H2R" type="hL" charge="0.047345"/>
   <Atom name="PA-H2S" type="hL" charge="0.047345"/>
   <Bond atomName1="PA-C116" atomName2="PA-H16R"/>
   <Bond atomName1="PA-C116" atomName2="PA-H16S"/>
   <Bond atomName1="PA-C116" atomName2="PA-H16T"/>
   <Bond atomName1="PA-C116" atomName2="PA-C115"/>
   <Bond atomName1="PA-C115" atomName2="PA-H15R"/>
   <Bond atomName1="PA-C115" atomName2="PA-H15S"/>
   <Bond atomName1="PA-C115" atomName2="PA-C114"/>
   <Bond atomName1="PA-C114" atomName2="PA-H14R"/>
   <Bond atomName1="PA-C114" atomName2="PA-H14S"/>
   <Bond atomName1="PA-C114" atomName2="PA-C113"/>
   <Bond atomName1="PA-C113" atomName2="PA-H13R"/>
   <Bond atomName1="PA-C113" atomName2="PA-H13S"/>
   <Bond atomName1="PA-C113" atomName2="PA-C112"/>
   <Bond atomName1="PA-C112" atomName2="PA-H12R"/>
   <Bond atomName1="PA-C112" atomName2="PA-H12S"/>
   <Bond atomName1="PA-C112" atomName2="PA-C111"/>
   <Bond atomName1="PA-C111" atomName2="PA-H11R"/>
   <Bond atomName1="PA-C111" atomName2="PA-H11S"/>
   <Bond atomName1="PA-C111" atomName2="PA-C110"/>
   <Bond atomName1="PA-C110" atomName2="PA-H10R"/>
   <Bond atomName1="PA-C110" atomName2="PA-H10S"/>
   <Bond atomName1="PA-C110" atomName2="PA-C19"/>
   <Bond atomName1="PA-C19" atomName2="PA-H9R"/>
   <Bond atomName1="PA-C19" atomName2="PA-H9S"/>
   <Bond atomName1="PA-C19" atomName2="PA-C18"/>
   <Bond atomName1="PA-C18" atomName2="PA-H8R"/>
   <Bond atomName1="PA-C18" atomName2="PA-H8S"/>
   <Bond atomName1="PA-C18" atomName2="PA-C17"/>
   <Bond atomName1="PA-C17" atomName2="PA-H7R"/>
   <Bond atomName1="PA-C17" atomName2="PA-H7S"/>
   <Bond atomName1="PA-C17" atomName2="PA-C16"/>
   <Bond atomName1="PA-C16" atomName2="PA-H6R"/>
   <Bond atomName1="PA-C16" atomName2="PA-H6S"/>
   <Bond atomName1="PA-C16" atomName2="PA-C15"/>
   <Bond atomName1="PA-C15" atomName2="PA-H5R"/>
   <Bond atomName1="PA-C15" atomName2="PA-H5S"/>
   <Bond atomName1="PA-C15" atomName2="PA-C14"/>
   <Bond atomName1="PA-C14" atomName2="PA-H4R"/>
   <Bond atomName1="PA-C14" atomName2="PA-H4S"/>
   <Bond atomName1="PA-C14" atomName2="PA-C13"/>
   <Bond atomName1="PA-C13" atomName2="PA-H3R"/>
   <Bond atomName1="PA-C13" atomName2="PA-H3S"/>
   <Bond atomName1="PA-C13" atomName2="PA-C12"/>
   <Bond atomName1="PA-C12" atomName2="PA-H2R"/>
   <Bond atomName1="PA-C12" atomName2="PA-H2S"/>
   <Atom name="PC-C11" type="cC" charge="0.78359"/>
   <Atom name="PC-O12" type="oC" charge="-0.599662"/>
   <Atom name="PC-O11" type="oS" charge="-0.454959"/>
   <Atom name="PC-C1" type="cA" charge="0.015894"/>
   <Atom name="PC-HR" type="hE" charge="0.119751"/>
   <Atom name="PC-HS" type="hE" charge="0.119751"/>
   <Atom name="PC-C2" type="cA" charge="0.09143"/>
   <Atom name="PC-HX" type="hE" charge="0.142617"/>
   <Atom name="PC-C3" type="cA" charge="0.010486"/>
   <Atom name="PC-HA" type="hE" charge="0.097145"/>
   <Atom name="PC-HB" type="hE" charge="0.097145"/>
   <Atom name="PC-O31" type="oT" charge="-0.422419"/>
   <Atom name="PC-P31" type="pA" charge="1.14988"/>
   <Atom name="PC-O32" type="oT" charge="-0.444224"/>
   <Atom name="PC-C31" type="cA" charge="0.183051"/>
   <Atom name="PC-H1A" type="hE" charge="0.056462"/>
   <Atom name="PC-H1B" type="hE" charge="0.056462"/>
   <Atom name="PC-C32" type="cA" charge="-0.01052"/>
   <Atom name="PC-H2A" type="hX" charge="0.080234"/>
   <Atom name="PC-H2B" type="hX" charge="0.080234"/>
   <Atom name="PC-N31" type="nA" charge="0.071798"/>
   <Atom name="PC-C33" type="cA" charge="-0.158752"/>
   <Atom name="PC-H3A" type="hX" charge="0.117715"/>
   <Atom name="PC-H3B" type="hX" charge="0.117715"/>
   <Atom name="PC-H3C" type="hX" charge="0.117715"/>
   <Atom name="PC-C34" type="cA" charge="-0.158752"/>
   <Atom name="PC-H4A" type="hX" charge="0.117715"/>
   <Atom name="PC-H4B" type="hX" charge="0.117715"/>
   <Atom name="PC-H4C" type="hX" charge="0.117715"/>
   <Atom name="PC-C35" type="cA" charge="-0.158752"/>
   <Atom name="PC-H5A" type="hX" charge="0.117715"/>
   <Atom name="PC-H5B" type="hX" charge="0.117715"/>
   <Atom name="PC-H5C" type="hX" charge="0.117715"/>
   <Atom name="PC-O33" type="oP" charge="-0.780684"/>
   <Atom name="PC-O34" type="oP" charge="-0.780684"/>
   <Atom name="PC-O21" type="oS" charge="-0.419523"/>
   <Atom name="PC-C21" type="cC" charge="0.770444"/>
   <Atom name="PC-O22" type="oC" charge="-0.596882"/>
   <Bond atomName1="PC-C11" atomName2="PC-O12"/>
   <Bond atomName1="PC-C11" atomName2="PC-O11"/>
   <Bond atomName1="PC-O11" atomName2="PC-C1"/>
   <Bond atomName1="PC-C1" atomName2="PC-HR"/>
   <Bond atomName1="PC-C1" atomName2="PC-HS"/>
   <Bond atomName1="PC-C1" atomName2="PC-C2"/>
   <Bond atomName1="PC-C2" atomName2="PC-HX"/>
   <Bond atomName1="PC-C2" atomName2="PC-C3"/>
   <Bond atomName1="PC-C2" atomName2="PC-O21"/>
   <Bond atomName1="PC-C3" atomName2="PC-HA"/>
   <Bond atomName1="PC-C3" atomName2="PC-HB"/>
   <Bond atomName1="PC-C3" atomName2="PC-O31"/>
   <Bond atomName1="PC-O31" atomName2="PC-P31"/>
   <Bond atomName1="PC-P31" atomName2="PC-O32"/>
   <Bond atomName1="PC-P31" atomName2="PC-O33"/>
   <Bond atomName1="PC-P31" atomName2="PC-O34"/>
   <Bond atomName1="PC-O32" atomName2="PC-C31"/>
   <Bond atomName1="PC-C31" atomName2="PC-H1A"/>
   <Bond atomName1="PC-C31" atomName2="PC-H1B"/>
   <Bond atomName1="PC-C31" atomName2="PC-C32"/>
   <Bond atomName1="PC-C32" atomName2="PC-H2A"/>
   <Bond atomName1="PC-C32" atomName2="PC-H2B"/>
   <Bond atomName1="PC-C32" atomName2="PC-N31"/>
   <Bond atomName1="PC-N31" atomName2="PC-C33"/>
   <Bond atomName1="PC-N31" atomName2="PC-C34"/>
   <Bond atomName1="PC-N31" atomName2="PC-C35"/>
   <Bond atomName1="PC-C33" atomName2="PC-H3A"/>
   <Bond atomName1="PC-C33" atomName2="PC-H3B"/>
   <Bond atomName1="PC-C33" atomName2="PC-H3C"/>
   <Bond atomName1="PC-C34" atomName2="PC-H4A"/>
   <Bond atomName1="PC-C34" atomName2="PC-H4B"/>
   <Bond atomName1="PC-C34" atomName2="PC-H4C"/>
   <Bond atomName1="PC-C35" atomName2="PC-H5A"/>
   <Bond atomName1="PC-C35" atomName2="PC-H5B"/>
   <Bond atomName1="PC-C35" atomName2="PC-H5C"/>
   <Bond atomName1="PC-O21" atomName2="PC-C21"/>
   <Bond atomName1="PC-C21" atomName2="PC-O22"/>
   <Bond atomName1="OL-C12" atomName2="PC-C21"/>
   <Bond atomName1="PA-C12" atomName2="PC-C11"/>
  </Residue>
```

**Comment by jchodera** [comment]
> To automate this, we would need to specify the following information for each lipid:

OK, we can encode this in a YAML file so that it is easy to extend if more are added.

Thanks for the clear step-by-step here.

**Comment by mpharrigan** [comment]
Looks like this is mostly settled but I'd like to just add that amber's script for splitting lipid residues is terrible, so it might behoove us to avoid it

**Comment by rafwiewiora** [comment]
Good stuff, thanks Peter!

I was wrong about the script - indeed there is a `charmmlipid2amber.py` script to convert the PDB from CHARMM to AMBER format, but we would have to add further code to OpenMM to read that format - so forget this. 

> The things I did were 1) prefix each atom name with the template name, since the templates had overlapping names, and 2) replace the <ExternalBond> tags with the appropriate <Bond> tags (the last two lines at the very end).

1) I already do for ions, just need to add code for 2) to the script.

> To automate this, we would need to specify the following information for each lipid:

What templates to merge.
What bonds to add between them.
What to name the merged residue.

> OK, we can encode this in a YAML file so that it is easy to extend if more are added.

Not even sure we need to encode any more stuff in the YAML - I suggest we have the script just do all combinations of head and tail groups, given small numbers of those. It will know which atoms to use for bonding from the files it's converting. Naming can be `head`-`tail1`-`tail2`. Sounds good?

**Comment by rafwiewiora** [comment]
This is remaining TODO.

**Comment by rafwiewiora** [comment]
This is still not done and I am busy with other things - can this way until after 7.2 or can I ask @jchodera to help out?

**Comment by jchodera** [comment]
@rafwiewiora : @peastman asked if we could specify the following for each lipid:

1. What templates to merge.
2. What bonds to add between them.
3. What to name the merged residue.

I suspect you never had a chance to compile this, but as luck may have it, this may already be available since the `charmmlipid2amber.py` script must already have this information encoded in it.

@peastman : You can download [AmberTools 17](http://ambermd.org/#AmberTools) or conda install it with
```bash
conda install ambertools=17 -c http://ambermd.org/downloads/ambertools/conda/
```
The script `charmmlipid2amber.py` appears to refer to a CSV file `$MINICONDA/ambertools-17.5-0/dat/charmmlipid2amber/charmmlipid2amber.csv` that contains information about how to split up CHARMM single-residue lipids into AMBER multi-residue lipids, so you should be able to translate this into information about which residue templates (and atom names) to join.

An example:
```
charmmlipid2amber.csv Version 2.0.4 (Lipid14 v2.0)
residue,order,search,replace,TER,num_atom
...
DAPE,0, C32 DAPE, C12 AR  ,True,129
DAPE,1, H2X DAPE, H2R AR  ,True,129
DAPE,2, H2Y DAPE, H2S AR  ,True,129
DAPE,3, C33 DAPE, C13 AR  ,True,129
...
DAPE,50, N   DAPE, N31 PE  ,True,129
DAPE,51, HN1 DAPE,HN1A PE  ,True,129
DAPE,52, HN2 DAPE,HN1B PE  ,True,129
...
```
which I think means that the CHARMM residue `DAPE` is actually made up of AMBER residues `AR` and `PE`, so these templates should be combined.

> It might be even easier to do it directly in ParmEd, but I've never worked with the code for that.

It may. I had never worked with ParmEd either...

**Comment by peastman** [comment]
That looks like exactly what we need.  I'm working on it now.

**Comment by peastman** [comment]
Where do I find the non-merged force fields?  I don't see any lipids at https://github.com/choderalab/openmm-forcefields/tree/master/amber/ffxml.

**Comment by jchodera** [comment]
Huh. Let me see...

**Comment by jchodera** [comment]
I'm guessing @rafwiewiora didn't convert them since he hadn't tackled the combining script.

You'll just have to add these to the `files/master.yaml` file in the [`amber/`](https://github.com/choderalab/openmm-forcefields/tree/master/amber) directory and then re-run the conversion. 

Amber lists the relevant files here:
![image](https://user-images.githubusercontent.com/3656088/31303295-1592cac0-aad9-11e7-9648-271047f20900.png)

**Comment by rafwiewiora** [comment]
I had converted Lipid14: https://github.com/choderalab/openmm/blob/forcefield_conversion_bonanza_amber16/devtools/forcefield-scripts/amber/ffxml/lipid14.xml

(https://github.com/pandegroup/openmm/issues/1611#issuecomment-285773135)

**Comment by jchodera** [comment]
@rafwiewiora : That was from AmberTools16, right? We can regenerate that for AmberTools17, but I can't find the `yaml` driver script that controls the `lipid14.xml` conversion. Can you point that out too?

**Comment by rafwiewiora** [comment]
I believe I did that by using the conversion script's single-file option, where you take that leaprc file out of AmberTools16 yes it was, and you do `python convert_amber.py --input-format "leaprc" leaprc.lipid14"

**Comment by rafwiewiora** [comment]
Correction to the above, you want to do:
`python convert_amber.py --input-format "leaprc" --input leaprc.lipid17 -v`

just tested on the leaprc.lipid17, works all good.

**Comment by rafwiewiora** [comment]
output lipid17.xml: https://gist.github.com/rafwiewiora/470743caeaa174da0aa4db5f536b2c4f

**Comment by rafwiewiora** [comment]
Also, if you're going to be converting the lipids, you might want to add a lipid test system for the energy test.

**Comment by peastman** [comment]
It looks like we're still missing one piece of information: the bonds between the component residues.  For example, charmmlipid2amber.csv tells me that POPC is made up of a PA, a PC, and an OL.  From lipid17.xml I can find that PC has two external bonds, one from C11 and one from C21.  One of those must connect to the PA and the other to the OL, but I can't determine which is which from these files.

The name charmmlipid2amber suggests this is for converting a CHARMM file.  Is that a particular file?  Does it have the missing information?

**Comment by jchodera** [comment]
> The name charmmlipid2amber suggests this is for converting a CHARMM file. Is that a particular file? Does it have the missing information?

The [Amber17 manual](http://ambermd.org/doc12/Amber17.pdf) describes its use:
![amber17-manual-lipids](https://user-images.githubusercontent.com/3656088/31308102-543bf6e2-ab3e-11e7-9bf2-900fd7e6202c.png)

To me, this suggests that the CHARMM36 residue topology definitions contain the information you need. You can get that information from a number of sources:
* the original [CHARMM `toppar/`](https://github.com/choderalab/openmm-forcefields/tree/master/charmm/toppar) files, which can be loaded into `parmed` as residue definitions
* the converted [CHARMM `ffxml` files](https://github.com/choderalab/openmm-forcefields/tree/master/charmm/ffxml)
* the [RCSB Ligand Expo](http://ligand-expo.rcsb.org/), which has reference small molecule definitions using the PDB naming convention (which would require a translation to the CHARMM convention)

**Comment by jchodera** [comment]
> By the way, looking at the CHARMM force field I notice you've separated out the water models into a water.xml file, but those same definitions are also still in charmm36.xml. Each residue should only appear in one file.

That file is from Mar 1, and I haven't done anything about the water issue yet (though I've just updated it to remind us to remove the default waters and create a meta-ffxml file for the default choices):
https://github.com/choderalab/openmm-forcefields/issues/34

**Comment by peastman** [comment]
Here's a script to do the translation.  It assumes `lipid17.xml`, `charmm36.xml`, and `charmmlipid2amber.csv` are all in the local directory, and it writes out the converted force field to `output.xml`.  It should be simple to adapt to however your conversion pipeline works.

```Python
import xml.etree.ElementTree as etree
from copy import deepcopy

# Read the input files.

charmmff = etree.parse('charmm36.xml')
amberff = etree.parse('lipid17.xml')
charmmResidues = charmmff.getroot().find('Residues').findall('Residue')
amberResidues = amberff.getroot().find('Residues').findall('Residue')
amberResMap = {}
for res in amberResidues:
    atoms = dict((atom.attrib['name'], atom) for atom in res.findall('Atom'))
    amberResMap[res.attrib['name']] = atoms
translations = {}
with open('charmmlipid2amber.csv') as input:
    # Skip the first two lines.
    input.readline()
    input.readline()
    for line in input:
        fields = line.split(',')
        mergedRes = fields[0]
        mergedAtom = fields[2].split()[0]
        originalAtom, originalRes = fields[3].split()
        translations[(mergedRes, mergedAtom)] = (originalRes, originalAtom)

# Remove all residues from the Amber file.

parentNode = amberff.getroot().find('Residues')
for res in amberResidues:
    parentNode.remove(res)

# Copy over the CHARMM residues, making appropriate replacements.

def translateResidue(residue):
    newres = deepcopy(residue)
    for atom in newres.findall('Atom'):
        key = (residue.attrib['name'], atom.attrib['name'])
        if key not in translations:
            return None # We don't have a translation.
        amberResName, amberAtomName = translations[key]
        if amberResName not in amberResMap or amberAtomName not in amberResMap[amberResName]:
            return None # We don't have a translation.
        amberAtom = amberResMap[amberResName][amberAtomName]
        for attrib in amberAtom.attrib:
            if attrib != 'name':
                atom.attrib[attrib] = amberAtom.attrib[attrib]
    return newres

for residue in charmmResidues:
    copy = translateResidue(residue)
    if copy is not None:
        parentNode.append(copy)
amberff.write('output.xml')
```

**Comment by jchodera** [comment]
Awesome! Can you make a pull request to https://github.com/choderalab/openmm-forcefields?

**Comment by peastman** [comment]
Where should it go?  I figured you would want to adapt it to fit into your input pipeline first.

**Comment by jchodera** [comment]
For now, it should go in [`amber/`](https://github.com/choderalab/openmm-forcefields/tree/master/amber) and refer to the CHARMM source files in [`../charmm/ffxml`](https://github.com/choderalab/openmm-forcefields/tree/master/charmm/ffxml). I'll add it to travis to make sure it's called in the right order.

We'll also want to add a note to the [`amber/README.md`](https://github.com/choderalab/openmm-forcefields/blob/master/amber/README.md) about what this script is and what it does.

**Comment by rafwiewiora** [comment]
@jchodera You'll need to add `leaprc.lipid17` to the `master.yaml` in Amber conversion too - I only did a manual conversion of that file for here.

**Comment by jchodera** [comment]
@peastman has completed this in #40.

**Comment by jchodera** [comment]
The remainder of this will be completed in https://github.com/choderalab/openmm-forcefields/pull/41

**Comment by jchodera** [comment]
@peastman: I've updated and documented your merging script [here](https://github.com/choderalab/openmm-forcefields/tree/master/amber), and have rerun it to generate [unmerged](https://github.com/choderalab/openmm-forcefields/blob/master/amber/ffxml/lipid17.xml) and [merged](https://github.com/choderalab/openmm-forcefields/blob/master/amber/ffxml/lipid17_merged.xml) lipid `ffxml` files. Can you try these out? If this works, the AMBER conversion should be complete.

Currently, only the unmerged lipids have an energy test that compares LEaP-generated system energies with `ffxml`-generated system energies. If I instead start with CHARMM-style lipids and convert them to AMBER style too, I can probably test to make sure the same potential energy is recovered.

**Comment by peastman** [comment]
I tested using `lipid17_merged.xml` to build a POPC membrane, and it seemed to work.

**Comment by jchodera** [comment]
Do you think it's critical I include a test of the merged energies too? If so, could you send me your POPC membrane PDB file?

**Comment by peastman** [comment]
I just emailed it to you.

**Comment by jchodera** [comment]
Just so I'm clear: Does this mean you think it's critical to test the merged `ffxml` gives identical energies to the original split `ffxml` energies for the appropriately-transformed PDB files (for lipids only in vacuum)?

**Comment by peastman** [comment]
I'm not sure what you mean.  We want to test that merging was done correctly.  We should have whatever tests are necessary to be confident of that.

**Comment by jchodera** [comment]
I've integrated lipid merging into the conversion script https://github.com/choderalab/openmm-forcefields/pull/52 prior to the testing stage.

**Comment by jchodera** [comment]
Tests were added in #52.
