### ISSUE TITLE
Ensure openmm-forcefields will be compatible with constant-pH

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#25]
We should make sure our constant-pH code http://github.com/choderalab/protons will generate ffxml files that work with the latest `simtk.openmm.app.ForceField` and the forcefields we convert here.

**Comment by bas-rustenburg** [comment]
I just checked my protein and ligand files. Everything is the same format, so it's all good to go from my end.

**Comment by jchodera** [comment]
Great!
