### ISSUE TITLE
Update and merge impropers PR

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#3]
Update https://github.com/pandegroup/openmm/pull/1560 so that old improper behavior remains as default but better amber agreement can be obtained via optional attribute.

**Comment by jchodera** [comment]
TO check: What happens with CHARMM

**Comment by rafwiewiora** [comment]
This is waiting for Peter's check and merge: https://github.com/pandegroup/openmm/pull/1560

**Comment by rafwiewiora** [comment]
TODO is also to add code to `ParmEd` to use the `ordering` attribute in `PeriodicTorsion` elements.

**Comment by rafwiewiora** [comment]
This is done.
