### ISSUE TITLE
CHARMM: Determine how to handle specification of impropers

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#33]
We may have wildcards

**Comment by ChayaSt** [comment]
@peastman and @jchodera: I looked into how CHARMM and ParmEd handle the atom ordering of impropers. 

According to the [CHARMM documentation](http://www.ks.uiuc.edu/Training/Tutorials/namd/namd-tutorial-unix-html/node24.html), the impropers must be defined in the residue topology:

> As noted above, the angle and dihedral terms will be autogenerated and are therefore not listed for this residue. The less common improper dihedrals (normally just called impropers), however, must be listed explicitly. In this case there are two impropers, which maintain the planarity of the peptide bonds. As with dihedrals, the order of atoms within an improper may be reversed. As shown below, impropers are specified by the IMPR statement followed by sets of four atoms, with the central atom to which the other three are bonded typically listed first.
> 
> IMPR N -C CA HN  C CA +N O
> 
Specifying the impropers eliminates ambiguity when the improper parameter type includes more than 1 wild type.
Since ParmEd parameterizes the structure from a `psf` file for the OpenMM system, it doesn't save the impropers in the residue template, it simply uses the order specified in the `psf` file and finds the correct improper parameter type. 
When OpenMM `forcefield.py` parameterizes the structure, it finds the impropers automatically which can create ambiguity when the improper parameter type includes 2 wild types. 

I would suggest adding an `<Improper>` tag to the `Residue` and modifying `forcefield.py` to use that order when the tag exists.

**Comment by peastman** [comment]
We need to give this some thought.  It reflects a major conceptual difference between how OpenMM and CHARMM handle torsions.

In OpenMM, improper torsions (like all other force field terms) are defined *implicitly*.  It considers every set of four atoms in the molecule that are bonded in a way that could form an improper torsion.  For each set it looks for a matching parameter definition.  If it finds one, it adds an improper with those parameters.  Otherwise, it skips that set of atoms.

In CHARMM, impropers are defined *explicitly*.  For each residue it has a list of exactly what impropers to include in that residue.  It adds those terms and no others.

Trying to make OpenMM handle them the way CHARMM does would require major architectural changes, as well as being a big conceptual change from how force fields currently work.  Possibly we just won't be able to get exact agreement on the impropers (just as the existing Amber force fields don't give exact agreement for impropers).  Do you have any data on how much disagreement we're currently getting?

**Comment by jchodera** [comment]
Doesn't OpenMM's approach lead to ambiguity in the way that atoms are enumerated into impropers, since the order in which improper parameter definitions are read matters? We tried to minimize this with the introduction of priorities in XML files, but this is still not ideal.

Unlike AMBER, CHARMM's approach eliminates any ambiguity using the simple solution of explicitly stating the impropers. We would be passing up an opportunity to get exact agreement with a well-defined specification, which does not seem appropriate.

Having mucked about with the internals of `ForceField`, it seems like this would be quite straightforward. We simply add an `implicit_impropers="false"` term to the `<PeriodicTorsionForce>` tag that causes [this block of improper enumeration](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L1959-L1994) to be skipped, and then either extend the `<CustomTorsionForce>` tag with the ability to handle impropers or add a `<HarmonicImproperForce>` with support for pulling impropers from the residue templates (much like `<NonbondedForce>` pulls charges from the residue templates). The result would require at most one additional force generator and would not interfere with existing parsing.

Another possibility is to take your earlier idea and split off a `CharmmForceField` class from `ForceField`, but the changes really seem so minimal that it doesn't seem necessary.

In future generation forcefields, we're trying to avoid this issue altogether through the use of ["trefoil impropers"](https://github.com/open-forcefield-group/smirnoff/blob/master/The-SMIRNOFF-force-field-format.md#improper-torsions), where the improper torsion (scaled by 1/6) is applied to every distinct sequence of atoms in the quartet.

**Comment by ChayaSt** [comment]
> Do you have any data on how much disagreement we're currently getting?

Once the patches are completed, I can start seeing how much disagreement we are getting.

> Having mucked about with the internals of ForceField, it seems like this would be quite straightforward. We simply add an implicit_impropers="false" term to the <PeriodicTorsionForce> tag that causes this block of improper enumeration to be skipped, and then either extend the <CustomTorsionForce> tag with the ability to handle impropers or add a <HarmonicImproperForce> with support for pulling impropers from the residue templates (much like <NonbondedForce> pulls charges from the residue templates). The result would require at most one additional force generator and would not interfere with existing parsing.

In CHARMM, the improper can be both harmonic and periodic so the changes will also have to be implemented in the `<CustomTorsionForce>`.

**Comment by peastman** [comment]
> Doesn't OpenMM's approach lead to ambiguity in the way that atoms are enumerated into impropers, since the order in which improper parameter definitions are read matters?

It's nothing to do with the order the definitions are read.  The force field spec requires that there must be a single unambiguous match for which parameters to use.  If that isn't the case, your force field definition is invalid.

The actual ambiguity comes from the matching of atom types.  If each of the four atoms has a different atom type, and there's at most one wildcard, the matching is unambiguous.  But if you have two wildcards, or alternatively if the improper involves two atoms with exactly the same atom type, then there are two possible orders.

**Comment by ChayaSt** [comment]
> The actual ambiguity comes from the matching of atom types. If each of the four atoms has a different atom type, and there's at most one wildcard, the matching is unambiguous. But if you have two wildcards, or alternatively if the improper involves two atoms with exactly the same atom type, then there are two possible orders.

This is what I think can happen here. The improper `NH1  X  X  H` is used in every peptide bond and includes two wildcards. There are more impropers with more than one wildcard. 
[Here](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/par_all36_prot.prm#L2188-L2196) and [here](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/par_all36_prot.prm#L2228-L2239)

**Comment by peastman** [comment]
Possibly the best solution is simply not to use wildcards in the definitions.  Let me explain what I mean.

OpenMM lists the impropers once, in the `<PeriodicTorsionForce>` tag.  That list determines what impropers to add and what parameters to use for them.  But CHARMM lists them twice: once to say which ones to add, and then again to say what parameters to use for them.  Your current implementation ignores that first list and builds the `<Improper>` tags solely based on the second list.  But it could build it based on the first list instead (taking parameter values from the second one, of course).  That would solve the problem.

The algorithm would go like this:

1. Make a list of every improper listed in any residue.

2. Represent each one by its atom types, and remove duplicates.

3. Write an `<Improper>` tag for each one.

You gave the example of the definition `NH1 X X H`.  That's ambiguous because it has wildcards.  But the definitions from the residues are unambiguous: each residue has an improper for atoms `N -C CA HN`, which have the types `NH1 C CT1 H`.  So write an `<Improper>` tag with those types.

**Comment by jchodera** [comment]
Aside from requiring additional infrastructure to essentially replicate the behavior of improper matching in ForceField to do the enumeration you suggest (all of which must be independently tested), that solution would result in an inextensible version of the CHARMM forcefield: Adding new or newly converted residues risks impropers not receiving parameters unless you convert the ENTIRE forcefield and additional residue over at once, which then is no better than setting the system up in CHARMM and using the CHARMM loaders.

**Comment by jchodera** [comment]
Also, that proposal would make a modular approach to small molecules that must be parameterized on the fly very difficult.

**Comment by peastman** [comment]
> Aside from requiring additional infrastructure to essentially replicate the behavior of improper matching in ForceField to do the enumeration you suggest

I don't know what you're talking about.  For each improper, you just do a simple loop over parameter definitions to find the one that matches.  Something along these lines:

```Python
for type1, type2, type3, type4, values in definitions:
  if a1 in (type1, 'X') and a2 in (type2, 'X') and a3 in (type3, 'X') and a4 in (type4, 'X'):
    # We have a match!
```

That is *way* simpler than what ForceField does, which involves looping over all possible sets of connected atoms and all possible permutations of them.

> Adding new or newly converted residues risks impropers not receiving parameters unless you convert the ENTIRE forcefield and additional residue over at once

Again, I have no idea what you're talking about.  This is a specific force field that defines parameters for a specific set of residues.  If an updated version of the force field comes out, we'll convert that new version all at once, and it will go in a new file with a new name.

> Also, that proposal would make a modular approach to small molecules that must be parameterized on the fly very difficult.

If you're parametrizing a small molecule, it's your job to provide all parameters needed for it, impropers along with everything else.  You can't make any assumptions about what files the user will or won't combine it with.

**Comment by peastman** [comment]
Also note that CGenFF is a separate force field from CHARMM36, and has its own list of atom types.  So small molecules are completely irrelevant to this discussion.

**Comment by jchodera** [comment]
CGenFF is a forcefield parameterization strategy for small organic molecules (similar to GAFF/Antechamber) and is [intended to be used alongside CHARMM36](https://www.charmm.org/ubbthreads/ubbthreads.php?ubb=showflat&Number=21133).

You may recall the motivation for my lab to convert forcefield parameters to OpenMM format in the first place is to permit facile comparisons of binding free energies between different forcefields. We will certainly not adopt a strategy that impedes or opposes this, since it is literally the major reason we are doing this conversion at all.

**Comment by peastman** [comment]
This discussion is only about how to support CHARMM36.  We aren't trying to supprt CGenFF in this release.  OpenMM doesn't currently have tools for parametrizing small molecules, and adding them is beyond the scope of 7.2.

If we decide to add a tool for parametrizing small molecules with CGenFF at some point in the future, we can discuss then how to implement it.  You're assuming we'll do it in one particular way: by putting all the parameters into a single XML file that users include along with their force field, then generating a separate file for each molecule that includes the residue template and nothing else.  That's one way of doing it, but it's not the only way, and it's not obvious to me it's necessarily the best way.  But that's a discussion for another time.

In any case, CGenFF is a separate force field from CHARMM36 with its own atom types.  That means that how we implement CHARMM36 doesn't limit our options for how to implement CGenFF in the future.

**Comment by jchodera** [comment]
> This discussion is only about how to support CHARMM36. We aren't trying to supprt CGenFF in this release. OpenMM doesn't currently have tools for parametrizing small molecules, and adding them is beyond the scope of 7.2.

`openmm-forcefields` will support small molecule parameterization with GAFF/Antechamber via the forcefield generator approach (https://github.com/choderalab/openmm-forcefields/issues/10), and we need to be sure the CGenFF scheme will work too. CGenFF is unfortunately not freely downloadable, but it is available at no cost to academics---we are just finishing up the paperwork to get a copy for internal use and want to make sure it will work.

Getting OpenMM into a shape where we will be able to support small molecules in a reasonably painless way is the major goal of our work on the ForceField conversions, so this is essential. 

> If we decide to add a tool for parametrizing small molecules with CGenFF at some point in the future, we can discuss then how to implement it. You're assuming we'll do it in one particular way: by putting all the parameters into a single XML file that users include along with their force field, then generating a separate file for each molecule that includes the residue template and nothing else. That's one way of doing it, but it's not the only way, and it's not obvious to me it's necessarily the best way. But that's a discussion for another time.

Yes. That's how we will support it now.

> In any case, CGenFF is a separate force field from CHARMM36 with its own atom types. That means that how we implement CHARMM36 doesn't limit our options for how to implement CGenFF in the future.

CGenFF is a CHARMM36-compatible forcefield for small organic molecules that adds additional atom types and parameters in a compatible way. We want to be sure to adopt a strategy that will allow us to use CGenFF-parameterized molecules that won't limit us in a silly way, like preventing us from having two small molecules in the same simulation because the enumerated impropers collide.

My group has put a lot of effort into these forcefield conversions with the sole purpose of being able to do comparisons of binding affinity calculations comparing between multiple forcefields. It's essential to get this into at least workable shape in this iteration. We can always improve things later, but we can't punt completely on at least making it possible to do the calculations we need.

It would be great to chat tomorrow about technical solutions for the remaining open questions. I've sent a calendar invite---just let me know if later in the day would work better.

**Comment by peastman** [comment]
> CGenFF is unfortunately not freely downloadable, but it is available at no cost to academics

Actually it is: http://mackerell.umaryland.edu/~kenno/cgenff/download.php#latest

> We want to be sure to adopt a strategy that will allow us to use CGenFF-parameterized molecules that won't limit us in a silly way, like preventing us from having two small molecules in the same simulation because the enumerated impropers collide.

That will definitely be essential.  But again, what we do here won't affect that.  CHARMM36 defines atom types used in a fixed set of molecules that it supports.  CGenFF has its own list of atom types for use in small molecules.  Any improper involving CGenFF atom types won't match any definition from CHARMM36, and vice versa.

**Comment by jchodera** [comment]
> Actually it is: http://mackerell.umaryland.edu/~kenno/cgenff/download.php#latest

CGenFF is both a parameter set (which *is* downloadable, as you note!) and a program to handle the assignments (which is not freely downloadable).

> That will definitely be essential. But again, what we do here won't affect that. CHARMM36 defines atom types used in a fixed set of molecules that it supports. CGenFF has its own list of atom types for use in small molecules. Any improper involving CGenFF atom types won't match any definition from CHARMM36, and vice versa.

We'll have to solve this problem all over again for the small molecules, and it's not clear your proposed solution would let us combine multiple distinct small molecules if there was potential for improper collisions within CGenFF.

It does appear that the latest CGenFF forcefield parameters have been folding into the c36 parameter sets distributed on the [Mackerell website](http://mackerell.umaryland.edu/charmm_ff.shtml). The CGenFF files are [currently included in our conversion](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/charmm36.yaml#L13-L14), along with the small molecules they distribute. This includes [a bunch of molecules with impropers that use CGenFF parameters](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/top_all36_cgenff.rtf). If any of those impropers collided with a new molecule we wanted to parameterize, we've screwed ourselves.

**Comment by peastman** [comment]
> It does appear that the latest CGenFF forcefield parameters have been folded into the c36 parameter sets distributed on the Mackerell website.

I just looked through those files, and CGenFF never uses wildcards at all, either for impropers or for anything else.  So once again, we're worrying about an issue that doesn't exist.

**Comment by jchodera** [comment]
Ah! That is very encouraging.

Two last potentially related issues:
* What if the same atom type is repeated? Isn't there ambiguity in assignment? For example, in `par_all36_cgenff.prm`:
```
CG2N1  NG2P1  NG2P1  NG2P1     40.0000  0     0.00 ! PROT 5.75->40.0 GUANIDINIUM (KK)
CG2O2  CG311  OG2D1  OG302     62.0000  0     0.00 ! PROT & LIPID WILDCARD; from MAS, methyl acetate; xxwy
CG2O2  CG321  OG2D1  OG311     65.0000  0     0.00 ! PROT & LIPID WILDCARD; ACEH, acetic acid; xxwy
```
* I'm still trying to wrap my head around this warning at the top of that file. Do you think it's relevant?
```
!  --------------------------------------------------------------------------  !
!  ORDER OF PREFERENCE FOR SORTING PARAMETERS:                                 !
!         + C < N < O < P < S < HALOGENS (LOW TO HIGH Z) < MISC. (BY Z) < H    !
!         + ATOMS TYPES WITHIN THE SAME ELEMENT ARE SORTED ALPHABETICALLY      !
!  --------------------------------------------------------------------------  !
!  RULES FOR SORTING THE COLUMS ON EACH LINE:                                  !
!         + IN BONDS, THE LOWEST PRIORITY ATOM ALWAYS COMES FIRST              !
!         + FOR ANGLES, IF COLUMN 3 HAS A LOWER PRIORITY THAN COLUMN 1,        !
!           COLUMNS 1 & 3 ARE SWAPPED                                          !
!         + FOR DIHEDRALS, IF COLUMN 3 HAS LOWER PRIORITY THAN COLUMN 2, THE   !
!           ORDER FOR THE ENTIRE DIHEDRAL IS REVERSED                          !
!         + FOR DIHEDRALS, IF COLUMNS 2 & 3 HAVE THE SAME PRIORITY, COLUMS     !
!           1 & 4 ARE CONSIDERED INSTEAD. IF 4 HAS LOWER PRIORITY THAN 1, THE  !
!           ORDER FOR THE ENTIRE DIHEDRAL IS REVERSED                          !
!         + FOR IMPROPERS, NO SORTING IS PERFORMED *AFTER* PARAMETRIZATION,    !
!           BUT THE FOLLOWING RULES APPLY *DURING* PARAMETRIZATION:            !
!               - COLUMN 1 IS ALWAYS THE CENTRAL ATOM                          !
!               - IF 2 OF THE SUBSTITUENTS HAVE IDENTICAL TYPES, THESE SHOULD  !
!                 BE IN COLUMNS 2 & 3 (BUT THEY CANNOT BE MOVED AROUND         !
!                 WITHOUT RE-OPTIMIZING THE PARAMETER)                         !
!               - IF THE SUBSTITUENTS ARE ALL DIFFERENT, COLUMNS 2, 3 & 4      !
!                 SHOULD BE SORTED BY INCREASING PRIORITY. COLUMNS 2 AND 3     !
!                 CAN BE SWAPPED WITHOUT CHANGING THE PARAMETER BUT OTHER      !
!                 PERMUTATIONS MANDATE RE-OPTIMIZATION                         !
!  --------------------------------------------------------------------------  !
!  PRIORITY OF COLUMNS FOR THE PURPOSE OF SORTING THE LINES IN EACH SECTION:   !
!           BONDS     -- 1,2                                                   !
!           ANGLES    -- 2,1,3                                                 !
!           DIHEDRALS -- 2,3,1,4                                               !
!           IMPROPERS -- 1,4,2,3                                               !
!  WHERE 1,2,3,4 INDICATE COLUMN NO, EG. DIHEDRALS ARE FIRST SORTED BY COLUMN  !
!  2, THEN (IF COLUMN 2 IS THE SAME) BY COLUMN 3, THEN BY COLUMN 1 AND THEN 4  !
!  --------------------------------------------------------------------------  !
```

**Comment by peastman** [comment]
I'm not sure what that means.  How certain are we that the order is really taken from the residue definition?  That sounds like it might be describing a set of rules for ordering them based on atom types.

**Comment by jchodera** [comment]
To summarize how this would work following our discussion:

In ParmEd, before we write out the improper torsions (but after loading all residue definitions and parameters), we will:
* For every residue or patch
   * For every `IMPR`oper in that residue
      * Find the improper parameter definition that matches
      * If this definition contains a wildcard, add a new improper parameter card that explicitly specifies the types in the current `IMPR`oper
* Remove all wildcard improper parameters
* Remove all duplicate improper parameters

Does that sound correct, @peastman ?

**Comment by peastman** [comment]
I think that should work.

**Comment by ChayaSt** [comment]
Not all atoms that are in the Patch `IMPR` are in the Patch entry. So to find the relevant atom types for the explicit improper, we need to know all the combination of patches and residues. Therefore, we should enumerate the explicit impropers at the same time we're enumerating the patches - residue combinations.

**Comment by jchodera** [comment]
New problem:

There are a surprising number of DELETE IMPR cards that delete impropers (all in top_all36_cgenff.rtf), which throws yet another wrench in our plans to handle impropers (#33). Implications of this are currently unknown, but here is an example of the cards:
```
PRES AMGA          0.00 ! C3H4O2 cacha
! patch combination:
! core residue Glutamic Acid CDCA Amide (GA) >> Alpha-Methyl Glu Acid CDCA Amide

                        !                                             OA1
                        !                                             ||
                        !                                       O24   CA--OA2--CH3(M)
                        !                                       ||    |
                        !                   OH     Me21   C22   C24   CC1   CC3   OG1(-0.5)
ATOM CC1  CG311    0.17 !                   |         \  /  \  /  \  /  \  /  \  /
ATOM HC1  HGA1     0.09 !                   C12 Me18   C20   C23   NH    CC2   CG
ATOM CA   CG2O2    0.90 !                  /  \ |     /                          \
ATOM OA1  OG2D1   -0.63 !                 C11  C13---C17                          OG2(-0.5)
ATOM OA2  OG302   -0.49 !            Me19 |    |     |
ATOM CM   CG331   -0.31 !           C1 | C9    C14   C16
ATOM HM1  HGA3     0.09 !          /  \|/  \  /  \  /
ATOM HM2  HGA3     0.09 !         C2   C10  C8    C15
ATOM HM3  HGA3     0.09 !         |    |    |
                        !         C3   C5   C7
                        !        / \  / \  /  \
                        !      HO   C4   C6    OH

                        !              Alpha-Methyl Glutamic Acid CDCA Amide

BOND OA2  CM
BOND CM   HM1  CM   HM2   CM   HM3
DELETE IMPR CA OA2 OA1 CC1
IMPR CA  CC1 OA1 OA2

IC CC1  CA   OA2  CM    1.5285  111.09 -178.91  115.08   1.4371
IC HM1  CM   OA2  CA    1.1113  109.28  179.56  115.08   1.3429
IC HM2  CM   OA2  CA    1.1136  110.99   60.48  115.08   1.3429
IC HM3  CM   OA2  CA    1.1135  110.99  -61.17  115.08   1.3429
```

**Comment by ChayaSt** [comment]
@jchodera, I don't think we can remove an improper since here the improper is given in atom names while the impropers in the `ffxml` is given in atom types. If we remove these deleted impropers, we can end up deleting an improper that is used for a different residue.

**Comment by peastman** [comment]
Hopefully that isn't an issue.  They're "deleting" an improper, but then adding it back again, just with a different atom order.  But have they also changed the types of some of those atoms?  If so, it'll just work.  The different atom types will signal ForceField to use the different order.

**Comment by jchodera** [comment]
I believe this is handled.
